# Jekyll Configuration for GitHub Pages
title: "Taehwa Hong - PhD Research"
description: "PhD Research Portfolio in Tactile Sensing and Robotics"
author: "Taehwa Hong"
email: "your.email@university.edu"
github_username: "ndolphin-github"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Site settings
baseurl: ""
url: "https://ndolphin-github.github.io"

# Navigation
nav_links:
  - title: "Home"
    url: "/#home"
  - title: "Research" 
    url: "/#research"
  - title: "Publications"
    url: "/#publications"
  - title: "Contact"
    url: "/#contact"

# SEO
lang: en_US
timezone: Asia/Seoul

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
